spring.application.name=drive

spring.datasource.url=jdbc:postgresql://localhost:5432/drive_java
spring.datasource.username=postgres
spring.datasource.password=2207

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB